name: testing

on:
  push:
    branches: main
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  docker:
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        version: [17, 18]

    steps:
      - uses: actions/checkout@v7

      - name: Docker version info
        run: |
          docker --version

          docker compose --version

      - name: Build kiwitcms/postgres:${{ matrix.version }}
        working-directory: ${{ matrix.version }}
        run: |
          docker build --sbom=true --provenance=mode=max -t kiwitcms/postgres:${{ matrix.version }} .

          docker images

  test:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7

      - name: Install packages used during container testing
        run: |
          # used in test scripts
          sudo apt-get install git make sscg

          # install beakerlib from source it doesn't ship DEB packages
          if [ ! -f "/usr/share/beakerlib/beakerlib.sh" ]; then
              git clone https://github.com/beakerlib/beakerlib.git
              sudo make -C beakerlib/ install
          fi

      - name: Run tests
        run: |
          ./testing/runner.sh
