name: testing

on:
  push:
    branches: main
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  docker:
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        version: [17, 18]

    steps:
      - uses: actions/checkout@v7

      - name: Docker version info
        run: |
          docker --version

          docker compose --version

      - name: Build kiwitcms/postgres:${{ matrix.version }}
        working-directory: ${{ matrix.version }}
        run: |
          docker build -t kiwitcms/postgres:${{ matrix.version }} .

          docker images --digests
